// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:
        'AIzaSyBfKNtrz3xz1TRkrSq80GhygUIlVtvm3EY', // TODO: Update with your Web API Key if different
    appId:
        '1:760708571143:web:placeholder', // TODO: Update with your Web App ID
    messagingSenderId: '760708571143',
    projectId: 'books-discovery-app-aba6e',
    authDomain: 'books-discovery-app-aba6e.firebaseapp.com',
    storageBucket: 'books-discovery-app-aba6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfKNtrz3xz1TRkrSq80GhygUIlVtvm3EY',
    appId: '1:760708571143:android:7b8f006bd7f80222adcaa2',
    messagingSenderId: '760708571143',
    projectId: 'books-discovery-app-aba6e',
    storageBucket: 'books-discovery-app-aba6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyBfKNtrz3xz1TRkrSq80GhygUIlVtvm3EY', // TODO: Update with your iOS API Key if different
    appId:
        '1:760708571143:ios:placeholder', // TODO: Update with your iOS App ID
    messagingSenderId: '760708571143',
    projectId: 'books-discovery-app-aba6e',
    storageBucket: 'books-discovery-app-aba6e.firebasestorage.app',
    iosBundleId:
        'com.digitalsolt.booksDiscoveryApp', // Replace with your bundle ID if different
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:
        'AIzaSyBfKNtrz3xz1TRkrSq80GhygUIlVtvm3EY', // TODO: Update with your macOS API Key if different
    appId:
        '1:760708571143:ios:placeholder', // TODO: Update with your macOS App ID
    messagingSenderId: '760708571143',
    projectId: 'books-discovery-app-aba6e',
    storageBucket: 'books-discovery-app-aba6e.firebasestorage.app',
    iosBundleId:
        'com.digitalsolt.booksDiscoveryApp', // Replace with your bundle ID if different
  );
}
